apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kc-consumer
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: kafka-consumer
    secret: kafka-consumer-secret
    serviceAccountsEnabled: true
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kc-producer
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: kafka-producer
    secret: kafka-producer-secret
    serviceAccountsEnabled: true