= AMQ Streams (Kafka) demo

The goal of this demo is to show some of the key capabilities of Red Hat AMQ Streams.

One of the key feature of *Red Hat® AMQ Streams* is bringing the power of *Apache Kafka* in *OpenShift Container Platform*, leveraging the Strimzi project.footnote:[https://strimzi.io/]

== Modules

The following modules were developed sequentially and often leverage previous configurations. However, the goal is to make them as independent as possible.

* xref:docs/kafka.adoc[Core Kafka installation and operations]
* xref:docs/rebalance.adoc[AMQ Streams Rebalancing] (Optional)
* xref:docs/client.adoc[Client scalability and resilience] (Optional)
* xref:docs/access.adoc[Accessing Kafka outside of the OpenShift cluster]
* xref:docs/keycloak-integration.adoc[Keycloak integration] (Optional)
* xref:docs/registry.adoc[Apicurio Schema Registry] (Optional)
* xref:docs/debezium.adoc [Debezium with Postgres] (Optional)
* xref:docs/clean.adoc[Environment clean up and troubleshooting] (Optional)
