---
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-ui
spec:
  hostname: kafka-console.${CLUSTER_DOMAIN}
  kafkaClusters:
  - name: my-cluster             # Name of the `Kafka` CR representing the cluster
    namespace: ${KAFKA_NAMESPACE}   # Namespace of the `Kafka` CR representing the cluster
    listener: plain                # Listener on the `Kafka` CR to connect from the console
    properties:
      values: []                    # Array of name/value for properties to be used for connections
                                    # made to this cluster
      valuesFrom: []                # Array of references to ConfigMaps or Secrets with properties
                                    # to be used for connections made to this cluster
    # If authentication is enabled
    # credentials:
    #   kafkaUser:
    #     name: console-kafka-user1   # Name of the `KafkaUser` resource used to connect to Kafka