---
kind: KafkaMirrorMaker2
apiVersion: kafka.strimzi.io/v1
metadata:
  name: outbound
  namespace: kafka-demo
spec:
  version: 3.9.0
  replicas: 1
  target:
    alias: cluster-b
    bootstrapServers: remote-cluster-kafka-bootstrap:9092
    groupId: mirrormaker2-cluster
    configStorageTopic: mirrormaker2-cluster-configs
    statusStorageTopic: mirrormaker2-cluster-status
    offsetStorageTopic: mirrormaker2-cluster-offsets
    tls:
      trustedCertificates: []
    authentication:
      type: plain
      username: $ConnectionString
      passwordSecret:
        secretName: eventhubssecret
        password: eventhubspassword
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      consumer.connections.max.idle.ms: 180000
      consumer.metadata.max.age.ms: 180000
  mirrors:
  - source:
      alias: cluster-a
      bootstrapServers: cluster-a-kafka-bootstrap:9092
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: A.*
    groupsPattern: A.*
