kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: event
  labels:
    strimzi.io/cluster: my-cluster
    app: my-kafka-demo
spec:
  partitions: 12
  replicas: 3
  config:
    segment.bytes: 100000