apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-config
  labels:
    app: kafka-producer
data:
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.my-kafka.svc:9092
  PRODUCER_TICK_FREQUENCY: "100"
  PRODUCER_PARTED: "false"
  PRODUCER_PARTITIONS: "0,3"