apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-config
  labels:
    app.kubernetes.io/name: kafka-producer
data:
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap:9092
  POSTGRESQL_SVC: "event-db:5432"
  PRODUCER_TICK_FREQUENCY: "100"
  PRODUCER_PARTED: "false"
  PRODUCER_PARTITIONS: "0,3"
  SEQUENCE_DB: "false"
