#####################################################################
# Producer:
# set the connector for the outgoing channel to `smallrye-kafka`
mp.messaging.outgoing.movies.connector=smallrye-kafka

# set the topic name for the channel to `movies`
mp.messaging.outgoing.movies.topic=movies

# No "value.serializer" because Quarkus can autodetect

# automatically register the schema with the registry, if not present
mp.messaging.outgoing.movies.apicurio.registry.auto-register=true
#####################################################################
# Consumer

# set the connector for the incoming channel to `smallrye-kafka`
mp.messaging.incoming.movies-from-kafka.connector=smallrye-kafka

# set the topic name for the channel to `movies`
mp.messaging.incoming.movies-from-kafka.topic=movies

# disable auto-commit, Reactive Messaging handles it itself
mp.messaging.incoming.movies-from-kafka.enable.auto.commit=false
mp.messaging.incoming.movies-from-kafka.auto.offset.reset=earliest

# No "value.deserializer" because Quarkus can autodetect

#####################################################################
# Registry config

%prod.mp.messaging.connector.smallrye-kafka.apicurio.registry.url=https://${SERVICE_REGISTRY_URL}
%prod.mp.messaging.connector.smallrye-kafka.apicurio.auth.service.token.endpoint=${OAUTH_TOKEN_ENDPOINT}
%prod.mp.messaging.connector.smallrye-kafka.apicurio.auth.client.id=${CLIENT_ID}
%prod.mp.messaging.connector.smallrye-kafka.apicurio.auth.client.secret=${CLIENT_SECRET}

%prod.mp.messaging.connector.smallrye-kafka.apicurio.registry.artifact.group-id=quarkus
%prod.mp.messaging.connector.smallrye-kafka.apicurio.registry.artifact.artifact-id=movies-value
%prod.mp.messaging.connector.smallrye-kafka.apicurio.registry.find-latest=true

# set true ONLY for DEV services:
# automatically register the schema with the registry
%prod.mp.messaging.outgoing.movies.apicurio.registry.auto-register=false
%dev.mp.messaging.outgoing.movies.apicurio.registry.auto-register=true

#####################################################################
# Kafka config

%prod.kafka.bootstrap.servers=${KAFKA_ROUTE}
%prod.kafka.ssl.truststore.location = ../truststore.jks
%prod.kafka.ssl.truststore.password = password
%prod.kafka.security.protocol=SSL