apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
---
# namespace dependent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: my-kafka
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa
  annotations:
    kubernetes.io/service-account.name: "grafana-serviceaccount"
type: kubernetes.io/service-account-token 