= Red Hat build of Debezium

Debezium is a distributed platform for capturing changes in database tables and delivering them to downstream systems in real time. It is built on top of Apache Kafka and uses Kafka Connect to connect to databases and stream change data to Kafka topics. Debezium is a popular choice for implementing data pipelines and microservices architectures.

Here's a summary of Debezium's key features:

1. **Real-time data capture:** Debezium captures changes in database tables as they occur, enabling real-time data processing and analysis.

2. **Change data capture (CDC):** Debezium provides CDC functionality, allowing you to track the full history of changes in your database tables.

3. **Kafka integration:** Debezium uses Kafka Connect to stream change data to Kafka topics, making it easy to integrate with Kafka-based systems.

4. **Database support:** Debezium supports a wide range of databases: Db2 (Linux only), MongoDB, MySQL, Oracle Database (LogMiner), PostgreSQL, SQL Server (including Azure SQL DB).

5. **Scalability:** Debezium is horizontally scalable, allowing you to handle increasing data volumes by adding more Debezium servers.

See more at the https://access.redhat.com/documentation/en-us/red_hat_build_of_debezium[official documentation page].

Learn about prerequisites at https://access.redhat.com/articles/4938181[Debezium Supported Configurations]

== Demo Prerequisites

* AMQ Streams Operator installed.
* Install Kafka cluster in `my-kafka` namespace following the instructions in this paragraph xref:kafka.adoc#create-kafka-broker-and-topic[Create Kafka Broker].

== Installation

Let's create a new project to include the Postgres DB and the Debezium instance:

[source,console]
----
oc new-project debezium
----

=== PostgreSQL

The following deployment uses the standard PostgreSQL 15 image available in the https://catalog.redhat.com/:[Red Hat Catalog].

In the configuration is extended to add the **write-ahead log**.

[source,console]
----
oc create configmap postgres-conf --from-file k8s/debezium/postgres.conf
oc apply -f k8s/debezium/01-postgres.yaml
----

The following commands will create a simple DB in Postgres:

[source,console]
----
set -x PGPOD (oc get pod -l app=postgres -ojsonpath='{.items[0].metadata.name}')
oc cp k8s/debezium/postgres-db-ddl.sql $PGPOD:/var/lib/pgsql/postgres-db-ddl.sql
oc exec -it $PGPOD -- psql -f /var/lib/pgsql/postgres-db-ddl.sql
----

TIP: If you are using Bash set the environment variable in this way: `export PGPOD=$(oc get pod -l app=postgres -ojsonpath='{.items[0].metadata.name}')`

=== Debezium

At its core, Debezium is a Kafka connector deployed on a Kafka Connect distributed server.

The following commands have a double effect:

1. A Kafka Connect image containing the Debezium libraries
2. Run Kafka Connect against this image 

[source,console]
----
oc create imagestream debezium-streams-connect
oc apply -f k8s/debezium/02-dbz-connect.yaml
----

To start the Debezium connector you have create the KafkaConnector resource with the following command:

[source,console]
----
oc apply -f k8s/debezium/03-dbz-connector.yaml
----

Issue the following command to check that it's running:

[source,console]
----
oc describe KafkaConnector dbz-sample-connector
----

You should see something similar:

----
Status:
  Conditions:
    Last Transition Time:  2023-11-25T14:45:44.792770738Z
    Status:                True
    Type:                  Ready
  Connector Status:
    Connector:
      State:      RUNNING
      worker_id:  10.128.1.190:8083
    Name:         dbz-sample-connector
    Tasks:
      Id:               0
      State:            RUNNING
      worker_id:        10.128.1.190:8083
    Type:               source
  Observed Generation:  1
  Tasks Max:            1
  Topics:
    debezium.public.customers
----

== Check the Debezium results

If everything works as expected, the `debezium.public.customers' topic should contain the information from the `customers' table in the Postgres DB.

The following command dump the topic content:

[source,console]
----
oc exec -n my-kafka -it my-cluster-kafka-0 -- bin/kafka-console-consumer.sh \
        --bootstrap-server my-cluster-kafka-bootstrap:9092 \
        --topic debezium.public.customers --from-beginning
----

In order to see the new messages flowing in real time, open a new terminal and insert a new record in the table:

[source,console]
----
set -x PGPOD (oc get pod -l app=postgres -ojsonpath='{.items[0].metadata.name}')
oc exec -it $PGPOD -- psql
----

On the `psql` command prompt, issue:

[source,sql]
----
\connect debezium;
INSERT INTO customers (name, email) VALUES ('Donato Marrazzo', 'donato@example.com');
exit
----

== Clean up

To remove everything:

[source,console]
----
oc delete project debezium
oc project my-kafka
oc delete kt dbz-connect-configs dbz-connect-offsets dbz-connect-status debezium.public.customers
----